# Generated by Django 5.2.4 on 2025-08-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjid', models.ImageField(unique=True, upload_to='')),
                ('subjects_name', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=50)),
            ],
        ),
    ]
