# Generated by Django 5.2.4 on 2025-09-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='sjid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
