# Generated by Django 4.2.7 on 2025-09-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_subjects_sjid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
